name: "Build distributions for major OS"

on:
  push:
    branches:
      - main

jobs:
  build_binaries:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            echo "Building for Linux."
            sudo apt update
            sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev
          elif [ "$RUNNER_OS" = "Windows" ]; then
            echo "Building for Windows."
            # choco install -y xcb-shape xcb-util-wm
          elif [ "$RUNNER_OS" = "macOS" ]; then
            echo "Building for macOS."
          else
            echo "OS $RUNNER_OS not supported."
          fi
        shell: "bash"

      - name: "Build application"
        run: |
          export CARGO_TARGET_DIR=dist/${{ matrix.os }}
          cargo build --release
        shell: "bash"

      - name: "Upload binary ${{ matrix.os }}"
        uses: actions/upload-artifact@master
        with:
          name: "gptc-${{ matrix.os }}"
          path: "dist/${{ matrix.os }}/release/gptc"

  open_pull_request:
    runs-on: ubuntu-latest

    needs: "build_binaries"

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Download binaries"
        uses: actions/download-artifact@master

      - name: "Commit changes and open pull request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
          # https://api.github.com/users/github-actions%5Bbot%5D
          sleep 30s
          PR_BRANCH="build-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git fetch --all
          ls -lha
          git rebase origin/main
          git switch -c $PR_BRANCH
          git add gptc-*
          git commit -m "Add binaries."
          git push -u origin $PR_BRANCH
          gh pr create -B main -t "[$GITHUB_REF_NAME]: Build gptc for all distros." -b "This pull request was generated from a Github Action and needs manual approval."
