name: "Build distributions for major OS"

on:
  push:
    branches:
      - main

jobs:
  build_binaries:
    runs-on: ${{ matrix.os }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            echo "Building for Linux."
            sudo apt update
            sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev
          elif [ "$RUNNER_OS" = "Windows" ]; then
            echo "Building for Windows."
            # choco install -y xcb-shape xcb-util-wm
          elif [ "$RUNNER_OS" = "macOS" ]; then
            echo "Building for macOS."
          else
            echo "OS $RUNNER_OS not supported."
          fi
        shell: "bash"

      - name: "Build application"
        run: |
          export CARGO_TARGET_DIR=dist/${{ matrix.os }}
          cargo build --verbose --release
        shell: "bash"

      - name: "Upload binary ${{ matrix.os }}"
        uses: actions/upload-artifact@master
        with:
          name: "gptc-${{ matrix.os }}"
          path: "dist/${{ matrix.os }}/release/gptc"

  open_pull_request:
    runs-on: ubuntu-latest

    needs: "build_binaries"

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Download binaries"
        uses: actions/download-artifact@master

      - name: "Commit changes and open pull request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "$GITHUB_ACTOR@no-reply.com"
          git config --global user.name "$GITHUB_ACTOR"
          git add .
          git switch -c build
          git commit -m "Add binaries."
          git push -u origin build
          gh pr create -B main -t "Build gptc for all distros." -b "This pull request was generated from a Github Action and needs manual approval."
