name: "Build distributions for major OS"

# Specifies the trigger for the workflow.
on:
  pull_request:
    types: [closed]

    branches-ignore: |
      "build-*"

# Defines the build and upload jobs for the gptc application.
jobs:
  build_binaries:
    # Runs the job on the specified operating system using a matrix.
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Specifies the latest version of Windows to use for the build.
        os: ["ubuntu-20.04", "macos-12", "windows-2022"]

    steps:
      # Checks out the repository.
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # Installs dependencies for the specified OS.
      - name: "Install dependencies"
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            echo "Building for Linux."
            ldd --version
            sudo apt update
            sudo apt install -y libxcb-shape0-dev libxcb-xfixes0-dev libxcb-xinput0 libxcb-render0
          elif [ "$RUNNER_OS" = "Windows" ]; then
            echo "Building for Windows."
            # choco install -y xcb-shape xcb-util-wm
          elif [ "$RUNNER_OS" = "macOS" ]; then
            echo "Building for macOS."
          else
            echo "OS $RUNNER_OS not supported."
          fi
        shell: "bash"

      # Builds the gptc application.
      - name: "Build application"
        run: |
          export CGO_ENABLED=0
          cargo build --release --target-dir "dist/${{ matrix.os }}"
        shell: "bash"

      # Uploads the built binary to the artifact storage.
      - name: "Upload binary ${{ matrix.os }}"
        uses: actions/upload-artifact@master
        with:
          name: "gptc-${{ matrix.os }}"
          path: |
            dist/${{ matrix.os }}/release/gptc.exe
            dist/${{ matrix.os }}/release/gptc

  # Defines the job to open a pull request after successful build and upload.
  open_pull_request:
    runs-on: ubuntu-latest

    needs: "build_binaries"

    # Grants write access to the repository content and pull requests.
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Checks out the repository.
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # Downloads the uploaded binary artifact from the previous build job.
      - name: "Download binaries"
        uses: actions/download-artifact@master

      # Commits the changes and opens a pull request.
      - name: "Commit changes and open pull request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Sets the name and email of the user for committing the changes.
          # Found the `user.email` and `user.name` attributes to reference "Github Bot" in
          # Github's UI.
          # https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
          # https://api.github.com/users/github-actions%5Bbot%5D

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Rebases the pull request branch on the latest changes from the main branch.
          git fetch --all
          git rebase origin/main

          # Switches to a new branch for the pull request.
          PR_BRANCH="build-$GITHUB_REF_NAME-$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT"
          git switch -c $PR_BRANCH
          rsync -ar gptc-* dist
          rm -rf gptc-*
          git add .
          git commit -m "Add binaries."
          git push -u origin $PR_BRANCH
          gh pr create -B main -t "[$GITHUB_REF_NAME] Build gptc for all distros." -b "This pull request was generated from a Github Action and needs manual approval."
          gh pr merge $PR_BRANCH -r

  # Creates a release tag containing all the new builds updated with the latest changes.
  open_release:
    runs-on: ubuntu-latest
    needs: "open_pull_request"

    permissions:
      contents: write

    steps:
      # Checks out the repository.
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # Commits the changes and opens a pull request.
      - name: "Commit changes and open pull request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Sets the name and email of the user for committing the changes.
          # Found the `user.email` and `user.name` attributes to reference "Github Bot" in
          # Github's UI.
          # https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
          # https://api.github.com/users/github-actions%5Bbot%5D

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Rebases the pull request branch on the latest changes from the main branch.
          git fetch --all
          git rebase origin/main

          # Create tag based on previous tag.
          CURR_TAG=$(git tag | head -n 1)
          CURR_TAG_NO_PATCH=$(echo $CURR_TAG | sed 's/.$//')
          CURR_PATCH=$(echo $CURR_TAG | rev | cut -d "." -f1 | rev)
          NEXT_PATCH=$(($CURR_PATCH + 1))
          NEXT_TAG="${CURR_TAG_NO_PATCH}${NEXT_PATCH}"

          # Copy binaries into a temporary location to avoid name conflicts.
          TMP_DIST=$(mktemp -d)
          cp dist/gptc-ubuntu-20.04/gptc "$TMP_DIST/gptc-ubuntu-20.04"
          cp dist/gptc-macos-12/gptc "$TMP_DIST/gptc-macos-12"
          cp dist/gptc-windows-2022/gptc.exe "$TMP_DIST/gptc-windows-2022.exe"

          # Create tag and upload binaries as artifacts.
          gh release create \
            --draft \
            --generate-notes \
            --latest \
            --title "Latest release changelog..." \
            $NEXT_TAG \
            $TMP_DIST/*

          # Remove temporary directory.
          rm -rf $TMP_DIST
